services:
  - type: web
    name: flask-tech-blog
    env: python
    buildCommand: pip install -r requirements.txt && FLASK_APP=app.py flask db upgrade
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_DEBUG
        value: 0
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: flask-tech-blog-db
          property: connectionString
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_SUBUSER
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: SITE_NAME
        value: Flask tech blog
      - key: MAX_CONTENT_LENGTH
        value: 5242880
      - key: REMEMBER_DAYS
        value: 30
      - key: SQLALCHEMY_ECHO
        value: 0

databases:
  - name: flask-tech-blog-db
    plan: free
